apiVersion: vpc.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Subnet
metadata:
  name: provider-jet-yc-subnet-a
spec:
  forProvider:
    name: provider-jet-yc-net-a
    networkId: enp80bgbqi2funfch70a
    v4CidrBlocks:
      - 10.0.0.0/24
    folderId: b1gl3b8gmea01lcfpifp
    zone: ru-central1-a
  providerConfigRef:
    name: default
---
apiVersion: vpc.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Subnet
metadata:
  name: provider-jet-yc-subnet-b
spec:
  forProvider:
    name: provider-jet-yc-net-b
    networkId: enp80bgbqi2funfch70a
    v4CidrBlocks:
      - 10.1.0.0/24
    folderId: b1gl3b8gmea01lcfpifp
    zone: ru-central1-b
  providerConfigRef:
    name: default
---
apiVersion: vpc.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Subnet
metadata:
  name: provider-jet-yc-subnet-c
spec:
  forProvider:
    name: provider-jet-yc-net-c
    networkId: enp80bgbqi2funfch70a
    v4CidrBlocks:
      - 10.2.0.0/24
    folderId: b1gl3b8gmea01lcfpifp
    zone: ru-central1-c
  providerConfigRef:
    name: default