apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: FolderIAMBinding
metadata:
  name: crossplane-preprod
spec:
  forProvider:
    serviceAccountsRef:
      - name: example-sa
    role: editor
    folderIdRef:
      name: example-folder
  providerConfigRef:
    name: example
