apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: FolderIAMBinding
metadata:
  name: crossplane-preprod
spec:
  forProvider:
    serviceAccountsRef:
      - name: example-sa
    role: editor
    folderId: ${data.folderId}
  providerConfigRef:
    name: default
