apiVersion: iam.yandex-cloud.jet.crossplane.io/v1alpha1
kind: ServiceAccountIamMember
metadata:
  name: provider-jet-yc-sa-iam-member
spec:
  forProvider:
    role: "storage.editor"
    member: "serviceAccount:ajei01nsfsp5fphnrqva"
    serviceAccountIdRef:
      name: provider-jet-yc-sa
  providerConfigRef:
    name: default