apiVersion: ydb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: DatabaseDedicated
metadata:
  name: database1
spec:
  forProvider:
    location:
    - region:
      - id: ru-central1
    name: test-ydb-dedicated
    networkIdRef:
      name: example-net
    subnetIdsRefs:
          - name: example-subnet-a
          - name: example-subnet-b
          - name: example-subnet-c
    resourcePresetId: medium
    scalePolicy:
    - fixedScale:
      - size: 1
    storageConfig:
    - groupCount: 1
      storageTypeId: ssd
    folderIdRef:
      name: example-folder
  providerConfigRef:
    name: example
---
apiVersion: vpc.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Subnet
metadata:
  name: example-subnet-b
spec:
  forProvider:
    name: example-subnet-b
    networkIdRef:
      name: example-net
    v4CidrBlocks:
      - 10.0.1.0/24
    folderIdRef:
      name: example-folder
    zone: ru-central1-b
  providerConfigRef:
    name: example
---
apiVersion: vpc.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Subnet
metadata:
  name: example-subnet-c
spec:
  forProvider:
    name: example-subnet-c
    networkIdRef:
      name: example-net
    v4CidrBlocks:
      - 10.0.2.0/24
    folderIdRef:
      name: example-folder
    zone: ru-central1-c
  providerConfigRef:
    name: example
