apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  namespace: default
type: Opaque
data:
  # 12345678
  password: MTIzNDU2Nzg=
---
apiVersion: mdb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: MongodbCluster
metadata:
  name: provider-jet-yc-mongodb
spec:
  forProvider:
    name: provider-jet-yc-mongodb
    environment: PRESTABLE
    networkIdRef:
      name: provider-jet-yc-net
    clusterConfig:
      - version: "4.2"
    resources:
      - diskSize: 16
        diskTypeId: network-hdd
        resourcePresetId: s2.micro
    maintenanceWindow:
      - type: ANYTIME
    database:
      - name: testdb
    user:
      - name: john
        passwordSecretRef:
          name: postgresql
          key: password
          namespace: default
        permission:
          - databaseName: testdb
    host:
      - zone: ru-central1-a
        subnetIdRef:
          name: provider-jet-yc-subnet-a
    folderIdRef:
      name: provider-jet-yc-folder
  providerConfigRef:
    name: default