apiVersion: v1
kind: Secret
metadata:
  name: redis
  namespace: default
type: Opaque
data:
  # 12345678
  password: MTIzNDU2Nzg=
---
apiVersion: mdb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: RedisCluster
metadata:
  name: provider-jet-yc-pg
spec:
  forProvider:
    name: provider-jet-yc-pg
    environment: PRESTABLE
    networkIdRef:
      name: provider-jet-yc-net
    config:
      - passwordSecretRef:
          name: redis
          key: password
          namespace: default
        version: "6.0"
    resources:
    - resourcePresetId: "hm1.nano"
      diskSize: 16
    maintenanceWindow:
      - type: ANYTIME
    host:
      - zone: ru-central1-a
        subnetId: e9b4bir2biatkf33vnju
    folderId: b1gl3b8gmea01lcfpifp
  providerConfigRef:
    name: default