apiVersion: datatransfer.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Endpoint
metadata:
  annotations:
    meta.upbound.io/example-id: datatransfer/v1alpha1/transfer
  labels:
    testing.upbound.io/example-name: pg_source
  name: pg-source
spec:
  forProvider:
    name: pg-test-source
    settings:
    - postgresSource:
      - connection:
        - onPremise:
          - hosts:
            - example.org
            port: 5432
        database: "prod-db"
        user: "pg-admin"
        password:
        - rawSecretRef:
            name: postgresql-local
            key: password
            namespace: default
        slotGigabyteLagLimit: 100
  providerConfigRef:
    name: default

---

apiVersion: datatransfer.yandex-cloud.jet.crossplane.io/v1alpha1
kind: Endpoint
metadata:
  annotations:
    meta.upbound.io/example-id: datatransfer/v1alpha1/transfer
  labels:
    testing.upbound.io/example-name: pg_target
  name: pg-target
spec:
  forProvider:
    name: pg-test-target2
    settings:
    - postgresTarget:
      - connection:
        - mdbClusterIdRef:
            name: example-pg
        databaseRef:
          name: pg-database1
        password:
        - rawSecretRef:
            name: postgresql
            key: password
            namespace: default
        userRef:
          name: pg-user1
  providerConfigRef:
    name: default

---

apiVersion: v1
kind: Secret
metadata:
  name: postgresql-local
  namespace: default
type: Opaque
data:
  # 12345678
  password: MTIzNDU2Nzg=
---

apiVersion: v1
kind: Secret
metadata:
  name: postgresql
  namespace: default
type: Opaque
data:
  # 12345678
  password: MTIzNDU2Nzg=
---
apiVersion: mdb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: PostgresqlCluster
metadata:
  name: example-pg
spec:
  forProvider:
    name: example-pg
    environment: PRESTABLE
    networkIdRef:
      name: example-net
    config:
      - version: "12"
        resources:
          - diskSize: 16
            diskTypeId: network-hdd
            resourcePresetId: s2.micro
        postgresqlConfig:
          max_connections: "395"
          enable_parallel_hash: "true"
          vacuum_cleanup_index_scale_factor: "0.2"
          autovacuum_vacuum_scale_factor: "0.34"
          default_transaction_isolation: "TRANSACTION_ISOLATION_READ_COMMITTED"
          shared_preload_libraries: SHARED_PRELOAD_LIBRARIES_AUTO_EXPLAIN
    maintenanceWindow:
      - type: WEEKLY
        day: SAT
        hour: 12
    host:
      - zone: ru-central1-a
        subnetIdRef:
          name: example-subnet-a
  providerConfigRef:
    name: default
  writeConnectionSecretToRef:
    name: postgress-conn
    namespace: default
    namespace: default
---
apiVersion: mdb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: PostgresqlUser
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/postgresqluser
  name: pg-user1
spec:
  forProvider:
    clusterIdRef:
      name: example-pg
    connLimit: 50
    name: user1
    passwordSecretRef:
      name: postgresql
      key: password
      namespace: default
    permission:
    settings:
      default_transaction_isolation: "read committed"
      log_min_duration_statement: "5000"
  providerConfigRef:
    name: default
---
apiVersion: mdb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: PostgresqlDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: mdb/v1alpha1/postgresqldatabase
  name: pg-database1
spec:
  forProvider:
    clusterIdRef:
      name: example-pg
    extension:
    - name: uuid-ossp
    - name: xml2
    lcCollate: en_US.UTF-8
    lcType: en_US.UTF-8
    name: db_name
    owner: user1
  providerConfigRef:
    name: default