apiVersion: kms.yandex-cloud.jet.crossplane.io/v1alpha1
kind: SymmetricKey
metadata:
  name: provider-jet-yc-sk
spec:
  forProvider:
    name: provider-jet-yc-sk
    description: provider-jet-yc created KMS key
    defaultAlgorithm: AES_128
    rotationPeriod: 8760h
    folderIdRef:
      name: provider-jet-yc-folder
  providerConfigRef:
    name: default