apiVersion: alb.yandex-cloud.jet.crossplane.io/v1alpha1
kind: TargetGroup
metadata:
  annotations:
    meta.upbound.io/example-id: alb/v1alpha1/targetgroup
  labels:
    testing.upbound.io/example-name: foo
  name: test-target-group
spec:
  forProvider:
    name: my-target-group
    target:
    - ipAddress: ${yandex_compute_instance.example-instance-1.network_interface.0.ip_address}
      subnetIdRef:
        name: example-subnet-a
    - ipAddress: ${yandex_compute_instance.example-instance-2.network_interface.0.ip_address}
      subnetIdRef:
        name: example-subnet-a
    folderIdRef:
      name: example-folder
  providerConfigRef:
    name: example
