apiVersion: kubernetes.yandex-cloud.jet.crossplane.io/v1alpha1
kind: NodeGroup
metadata:
  name: provider-jet-yc-nodegroup
spec:
  forProvider:
    clusterIdRef:
      name: provider-jet-yc-cluster
    name: provider-jet-yc-cluster
    description: provider-jet-yc cluster
    version: "1.21"
    instanceTemplate:
      - platformId: "standard-v2"
        networkInterface:
          - nat: true
            subnetIdsRef:
              - name: provider-jet-yc-subnet-a
        resources:
          - memory: 2
            cores: 2
        bootDisk:
          - type: "network-hdd"
            size: 64
        schedulingPolicy:
          preemptible: true
    scalePolicy:
      - fixedScale:
          - size: 1
    allocationPolicy:
      - location:
          - zone: "ru-central1-a"
    maintenancePolicy:
      - autoUpgrade: true
        autoRepair: true
        maintenanceWindow:
          - startTime: "15:00"
            duration: "3h"
            day: "monday"
          - startTime: "10:00"
            duration: "4h30m"
            day: "friday"
  providerConfigRef:
    name: default